server:
  port: 18013
  servlet:
    # 应用的访问路径
    context-path: /
    tomcat:
      uri-encoding: UTF-8
      # 连接数满后的排队数，默认为100
      accept-count: 1000
      threads:
        # 最大线程数，默认为200
        max: 800
        # 启动初始化的线程数，默认值10
        min-spare: 100

debug: true

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${user.home}/logs/${spring.application.name}

x-starter:
  swagger:
    enabled: true
    base-package: com.xfeel.cloud.message.user.web.controller
  validations:
    enabled: true
    reloadable: false
    basename: i18n/validations
  druid:
    enabled: true

  biz:
    message:
      group-send-limit: 20

spring:
  application:
    name: message-user-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${mysql.host:mysql}:${mysql.port:3306}/${mysql.name:message}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${mysql.username:xcloud}
    password: ${mysql.password:Xcloud_ready_2_go}
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: admin
        login-password: Druid_ready_2_go
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

  data:
    mongodb:
      uri: mongodb://${mongo.user:xcloud}:${mongo.password:Message_ready_2_go}@${mongo.host:mongo}/${mongo.name:message}

  # 文件上传
  servlet:
    multipart:
      enabled: true
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 30MB

  jpa:
    hibernate:
      ddl-auto: update
  #  zipkin:
  #    sender:
  #      type: kafka
  sleuth:
    jdbc:
      p6spy:
        tracing:
          include-parameter-values: true

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092

  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
          loggerLevel: basic
    hystrix:
      enabled: false
    compression:
      request:
        enabled: true
        mime-types: text/xml,application/xml,application/json
        min-request-size: 2048
      response:
        enabled: true
        useGzipDecoder: true

  hystrix:
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            strategy: SEMAPHORE
            timeoutInMilliseconds: 60000

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3600

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
    default-property-inclusion: always

  main:
    allow-bean-definition-overriding: true

  devtools:
    restart:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      log-file: spy.log
      tracing:
        include-parameter-values: true #spring.sleuth.jdbc.p6spy.tracing.include-parameter-values
